name: Build and Deploy (2)

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      matrix:
        ocaml-version:
          - 4.14.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          opam-local-packages: nuscr/*.opam

      - name: Cache opam
        uses: actions/cache@v2
        with:
          path: _opam
          key: ${{ runner.os }}-${{ matrix.ocaml-version }}-${{ hashFiles('dune-project') }}

      # - run: cd SynMPST && opam install . --deps-only --with-doc --with-test

      - run: opam install menhir dune js_of_ocaml js_of_ocaml-ppx js_of_ocaml-tyxml

      - run: opam exec -- dune build

      - name: Deploy live version
        run: WHERE=../site opam exec -- make -C web deploy

      - name: Actually deploy
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: site
