name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        ocaml-version:
          - 4.14.x

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - name: Cache opam
        uses: actions/cache@v2
        with:
          path: _opam
          key: ${{ runner.os }}-${{ matrix.ocaml-version }}-${{ hashFiles('dune-project') }}

      - run: opam install . --deps-only

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

      # - run: opam install ocamlformat=0.22.4

      - run: opam exec -- dune build
